name: supabase_auth_ui
description: Simple, opinionated widgets for Supabase Auth
topics:
  - auth
  - authentication
  - supabase
  - ui
  - widget
version: 0.6.0
homepage: https://sealambda.com
repository: https://github.com/sealambda/flutter-auth-ui
issue_tracker: https://github.com/sealambda/flutter-auth-ui/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  font_awesome_flutter: ^10.6.0
  supabase_flutter: ^2.5.6
  email_validator: ^3.0.0
  phone_form_field: ^10.0.1

  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0

  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13

  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:
  assets:
    - assets/logos/

screenshots:
  - description: Supabase Auth UI
    path: screenshots/supabase_auth_ui.png
